### ISSUE TITLE
Would you share you visionOS app to our Demo Share Platform

### ISSUE THREAD

**Issue by SketchK** [li3zhen1/Grape#27]
Hello, I am Zhang Siqi, the person in charge of [SwitGG](https://swiftgg.team/) and [XReality.Zone](https://xreality.zone/).

Events hosted by these two communities have been officially recommended by Apple multiple times, and you can still find our [SwiftGG: WWDC.Playground event](https://swift.gg/wwdc23/) organized this year on the [Beyond WWDC official website](https://developer.apple.com/wwdc23/beyond-wwdc/).

I am reaching out to you because I heard that you have a demo for visionOS. Would you be interested in publishing it on our visionOS app exchange platform?

Application Exchange Platform: https://github.com/XRealityZone/Let-us-xrOS/blob/main/README.md
Application Data Repository: https://github.com/XRealityZone/XRApps/blob/main/README.md

Here is a brief explanation of why we are undertaking this project.

With the release of Apple Vision Pro this summer, the era of spatial computing is upon us, inspiring tech enthusiasts and developers to think about crafting unique three-dimensional applications with new interactions, systems, and hardware.

Since the WWDC 2023 keynote, social media has been abuzz with stunning visuals and demo videos of visionOS apps, but due to the Apple Vision Pro not being officially released yet, it's difficult for us to try out other developers' creations.

To address this, we have developed the Let’s xrOS app, which allows you to test out visionOS apps from other creators in the community, giving you early access to the charm of spatial computing devices.

We hope this tool will enhance the frequency of exchanges between developers and promote the growth of the entire community.

I look forward to your response!

Wishing you all the best!

P.S.: Please do not publicize this app and data repository yet. Let's wait for our official announcement tomorrow, and then you can help us promote it. For now, my main objective is to gather some developers' apps to generate interest in the store!

**Comment by li3zhen1** [comment]
Hi Siqi,

Thank you for reaching out and providing details about your visionOS app exchange platform. 

I'm definitely interested in sharing my project on your platform. But I'll need some time to upload my project since I’ve been quite occupied with coursework recently.

Best wishes, and I'm excited to be a part of this community!

**Comment by SketchK** [comment]
Thank you!
Waiting for your response!
