### ISSUE TITLE
Make the view scrollable / pan to move

### ISSUE THREAD

**Issue by larsmathuseck** [li3zhen1/Grape#42]
Thanks for your great work!
Is it possible to make the view scrollable, i.e., make the view larger than the screen and use pan and zoom to navigate around?
I tried to wrap the view inside a scrollview, but without success.
Also, the pinch to zoom gesture seems to be buggy.

Thanks again for your support.

**Comment by li3zhen1** [comment]
Hi! I've added drag support for moving entire graph when the gesture happens background (which should work similar to scrolling). Pinch to zoom is also fixed.

If you do want to put a large graph in a scrollview, you probably can set a big frame size and put it into a scrollview. (If gesture conflicts occurs in this case, please raise a new issue.)


Thank you!

**Comment by nickpapciak** [comment]
how can I opt-out of this and make my view not scrollable / panable? I embedded a ForceDirectedGraph within a larger view that has an onTapGesture, but when I click within the background it doesn't work, it just scrolls.

**Comment by li3zhen1** [comment]
Hi @nickpapciak , a workaround would be using `.allowHitTesting(false)`. I'll revisit the API later.

**Comment by nickpapciak** [comment]
Yes I was thinking so but that disables dragging the graph nodes. I can make a PR with the change if you'd like. In terms of API I would probably just make a new init with an isBackgroundDraggable option

**Comment by li3zhen1** [comment]
Sure. That'd be great!
