### ISSUE TITLE
Dragging nodes does not work on iOS

### ISSUE THREAD

**Issue by wilsongoode** [li3zhen1/Grape#43]
Several of the examples include the ability to drag nodes. When built for macOS, the nodes can be tapped (clicked) and dragged. When built for iOS, only tapping works. 

I discovered this first by incorporating this library in my iOS app, then adding handlers [as documented](https://li3zhen1.github.io/Grape/Grape/documentation/grape/forcedirectedgraph). I spent a long time trying to understand why I could only get `onNodeTapped` to work, adding and removing handlers to see if they made any difference. I was not able to understand why by reading your code, but I assume I just missed something.

I eventually decided to build and run the [examples project](https://github.com/li3zhen1/Grape/tree/main/Examples/ForceDirectedGraphExample) on macOS, then on an iOS simulator. This is when I discovered that they do not perform the same.

Any ideas what might be causing this?

Thanks, Wilson

**Comment by li3zhen1** [comment]
Hi, this is fixed. Thanks!
